set(can_build true)
set(doc_classes
        VisualScriptBasicTypeConstant
        VisualScriptBuiltinFunc
        VisualScriptClassConstant
        VisualScriptComment
        VisualScriptCondition
        VisualScriptConstant
        VisualScriptConstructor
        VisualScriptCustomNode
        VisualScriptDeconstruct
        VisualScriptEditor
        VisualScriptEmitSignal
        VisualScriptEngineSingleton
        VisualScriptExpression
        VisualScriptFunctionCall
        VisualScriptFunctionState
        VisualScriptFunction
        VisualScriptGlobalConstant
        VisualScriptIndexGet
        VisualScriptIndexSet
        VisualScriptInputAction
        VisualScriptIterator
        VisualScriptLocalVarSet
        VisualScriptLocalVar
        VisualScriptMathConstant
        VisualScriptNode
        VisualScriptOperator
        VisualScriptPreload
        VisualScriptPropertyGet
        VisualScriptPropertySet
        VisualScriptResourcePath
        VisualScriptReturn
        VisualScriptSceneNode
        VisualScriptSceneTree
        VisualScriptSelect
        VisualScriptSelf
        VisualScriptSequence
        VisualScriptSubCall
        VisualScriptSwitch
        VisualScriptTypeCast
        VisualScriptVariableGet
        VisualScriptVariableSet
        VisualScriptWhile
        VisualScript
        VisualScriptYieldSignal
        VisualScriptYield 
)
set(doc_path doc_classes)
