#pragma once

#define VERSION_SHORT_NAME "@short_name@"
#define VERSION_NAME "@name@"
#define VERSION_MAJOR @major@
#define VERSION_MINOR @minor@
#define VERSION_PATCH @patch@
#define VERSION_STATUS "@status@"
#define VERSION_BUILD "@VERSION_BUILD@"
#define VERSION_MODULE_CONFIG "@VERSION_MODULE_CONFIG@"
#define VERSION_YEAR @VERSION_YEAR@
#define VERSION_WEBSITE @VERSION_WEBSITE@
#define VERSION_DOCS_URL "@VERSION_WEBSITE@"

